export const projects = [
  {
    id: 1,
    title: "Terakins Global",
    tags: ["web", "html", "css", "react", "tailwind", "framer-motion"],
    desc: "A full-featured e-commerce platform for a Nigerian wellness drinks brand. Showcases products like Tigernut Milk, Herbal Zobo, and Regular Zobo with dynamic size/price selection, an Add to Cart system, and a clean, brand-consistent UI built to convert.",
    image: "/projects/zoboexensions.png",
    live: "https://terakinsglobal.vercel.app/",
    code: "https://github.com/Donvictory/terakinsglobal",
  },
  {
    id: 2,
    title: "Browser Extension",
    tags: ["html", "css", "javascript"],
    desc: "A browser extension that provides a seamless user experience.",
    image: "/projects/fem challenge.png",
    live: "https://fem-browser-extensions.vercel.app/",
    code: "https://github.com/Donvictory/fem-challenge",
  },
  {
    id: 3,
    title: "Naija Tax",
    tags: ["html", "css", "javascript"],
    desc: "A Nigerian tax literacy tool that helps users understand their tax status in under 3 minutes. Users answer quick questions to find out how the 2026 tax reforms apply to them, what actions to take, and what reliefs they can claim — making tax compliance accessible to everyday Nigerians.",
    image: "/projects/naija-tax.png",
    live: "https://naija-tax-siit.vercel.app/",
    code: "https://github.com/Donvictory/naija-tax",
  },
  {
    id: 4,
    title: "DriftCare NG",
    tags: ["react", "framer-motion", "tailwind"],
    desc: "DriftCare NG is an AI-powered preventive health drift monitor built for Nigeria. We detect behavioral and symptom drift from your personal health baseline — and alert you to consult a doctor before conditions become emergencies.",
    image: "/projects/drift-care.png",
    live: "https://driftcare.vercel.app/",
    code: "https://github.com/Donvictory/driftcare-ng",
  },
];
